export function CompStyles(){
    const styles = {
        //Loader
        loaderOverlay: {
            position: "fixed",
            inset: 0,
            background: "rgba(255,245,240,0.92)",
            backdropFilter: "blur(10px)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 1000,
        },
        loaderCard: {
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            gap: 12,
            animation: "fadeIn 0.4s ease",
        },
        spinnerRing: {
            position: "relative",
            width: 100,
            height: 100,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
        },
        ringSegment: {
            position: "absolute",
            inset: 0,
            borderRadius: "50%",
            border: "4px solid transparent",
        },
        ring1: {
            borderTopColor: "#c9184a",
            animation: "spin1 1s linear infinite",
        },
        ring2: {
            inset: 10,
            borderTopColor: "#e07b39",
            animation: "spin2 0.8s linear infinite",
        },
        ring3: {
            inset: 20,
            borderTopColor: "#ff9f1c",
            animation: "spin3 1.2s linear infinite",
        },
        loaderEmoji: {
            fontSize: 26,
            zIndex: 1,
        },
        loaderTitle: {
            fontSize: 20,
            fontWeight: 800,
            color: "#1a0a00",
            margin: 0,
            fontFamily: "'Georgia', serif",
        },
        loaderSub: {
            fontSize: 14,
            color: "#9e7060",
            margin: 0,
            textAlign: "center",
            maxWidth: 260,
            fontFamily: "'Verdana', sans-serif",
        },
        progressTrack: {
            width: 240,
            height: 6,
            background: "#fde0e9",
            borderRadius: 3,
            overflow: "hidden",
            marginTop: 8,
        },
        progressBar: {
            height: "100%",
            background: "linear-gradient(90deg, #c9184a, #e07b39, #ff9f1c)",
            borderRadius: 3,
            animation: "progressAnim 2.6s ease-out forwards",
        },
        
        // Step bar
        stepBar: {
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            marginBottom: 4,
            zIndex: 1,
        },
        stepItem: {
            display: "flex",
            alignItems: "center",
        },
        stepDot: {
            width: 14,
            height: 14,
            borderRadius: "50%",
            transition: "all 0.35s ease",
        },
        stepLine: {
            width: "clamp(32px, 6vw, 64px)",
            height: 2,
            transition: "background 0.35s ease",
        },
        stepLabels: {
            display: "flex",
            justifyContent: "center",
            gap: "clamp(12px, 4vw, 32px)",
            marginBottom: 28,
            zIndex: 1,
        },
        stepLabel: {
            fontSize: "clamp(10px, 1.5vw, 12px)",
            fontFamily: "'Verdana', sans-serif",
            transition: "all 0.3s ease",
            letterSpacing: 0.5,
        },

        //Mandala
        mandala1: {
            position: "fixed",
            top: "-220px",
            right: "-220px",
            width: 450,
            height: 450,
            opacity: 1,
            overflow: "visible",
            pointerEvents: "none",
            transformOrigin: "center center",
            willChange: "transform",
            animation: "rotateAnticlock 60s linear infinite",
        },

        mandala2: {
            position: "fixed",
            top: "-220px",
            left: "-220px",
            width: 450,
            height: 450,
            opacity: 1,
            overflow: "visible",
            pointerEvents: "none",
            transformOrigin: "center center",
            willChange: "transform",
            animation: "rotateClock 60s linear infinite",
        },

        // Header
        header: {
            textAlign: "center",
            marginBottom: 32,
            zIndex: 1,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            gap: 8,
        },
        headerDecor: {
            fontSize: 22,
            color: "#e07b39",
            letterSpacing: 8,
        },
        heroTitle: {
            fontSize: "clamp(2.2rem, 6vw, 3.8rem)",
            fontWeight: 900,
            lineHeight: 1.1,
            color: "#1a0a00",
            margin: 0,
            letterSpacing: "-0.5px",
        },
        heroAccent: {
            color: "#c9184a",
            fontStyle: "italic",
        },
        heroSub: {
            color: "#7b4f3a",
            fontSize: "clamp(0.9rem, 2.5vw, 1.1rem)",
            margin: 0,
            letterSpacing: 1,
            fontFamily: "'Verdana', sans-serif",
        },

        // Card
        card: {
            background: "rgba(255,255,255,0.92)",
            backdropFilter: "blur(12px)",
            borderRadius: 24,
            padding: "clamp(24px, 5vw, 48px)",
            width: "100%",
            maxWidth: 700,
            boxShadow: "0 20px 60px #c9184a18, 0 2px 8px #0002",
            border: "1px solid #fce4ec",
            zIndex: 1,
        },

        stepTitle: {
            fontSize: "clamp(1.2rem, 3vw, 1.6rem)",
            fontWeight: 800,
            color: "#1a0a00",
            margin: "0 0 4px",
        },
        stepHint: {
            color: "#9e7060",
            fontSize: 14,
            margin: "0 0 20px",
            fontFamily: "'Verdana', sans-serif",
        },

        // Trip Type Tiles
        tileGrid: {
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(130px, 1fr))",
            gap: 12,
            marginBottom: 28,
        },
        tile: {
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            padding: "16px 8px",
            borderRadius: 16,
            cursor: "pointer",
            transition: "all 0.25s ease",
            position: "relative",
            fontFamily: "'Georgia', serif",
        },
        tileIcon: { fontSize: 28, marginBottom: 6 },
        tileLabel: { fontSize: 13, fontWeight: 600 },
        tileCheck: {
            position: "absolute",
            top: 8,
            right: 10,
            fontSize: 12,
            fontWeight: 900,
        },

        // Search + States
        searchInput: {
            width: "100%",
            padding: "12px 16px",
            borderRadius: 12,
            border: "1.5px solid #f8bbd0",
            fontSize: 15,
            color: "black",
            marginBottom: 14,
            outline: "none",
            background: "#fff9fb",
            fontFamily: "'Verdana', sans-serif",
            boxSizing: "border-box",
            transition: "border-color 0.2s",
        },
        stateGrid: {
            display: "flex",
            flexWrap: "wrap",
            gap: 8,
            maxHeight: 260,
            overflowY: "auto",
            marginBottom: 24,
            paddingRight: 4,
        },
        stateChip: {
            padding: "7px 14px",
            borderRadius: 20,
            fontSize: 13,
            cursor: "pointer",
            transition: "all 0.2s ease",
            fontFamily: "'Verdana', sans-serif",
        },

        // Season / Duration cards
        seasonGrid: {
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(120px, 1fr))",
            gap: 14,
            marginBottom: 28,
        },
        seasonCard: {
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            padding: "18px 8px",
            borderRadius: 18,
            cursor: "pointer",
            transition: "all 0.25s ease",
            fontFamily: "'Georgia', serif",
        },

        // Summary (Step 4)
        summaryGrid: {
            display: "flex",
            flexDirection: "column",
            gap: 16,
            background: "#fff9f7",
            borderRadius: 16,
            padding: 20,
            marginBottom: 24,
            border: "1px solid #fde0e9",
        },
        summaryBlock: {
            display: "flex",
            flexDirection: "column",
            gap: 8,
        },
        summaryRow: {
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            gap: 16,
        },
        summaryLabel: {
            fontSize: 12,
            fontWeight: 700,
            color: "#c9184a",
            textTransform: "uppercase",
            letterSpacing: 1.2,
            fontFamily: "'Verdana', sans-serif",
        },
        summaryValue: {
            fontSize: 16,
            fontWeight: 600,
            color: "#1a0a00",
        },
        chipRow: {
            display: "flex",
            flexWrap: "wrap",
            gap: 6,
        },
        chip: {
            padding: "5px 12px",
            borderRadius: 20,
            fontSize: 13,
            fontWeight: 600,
            fontFamily: "'Verdana', sans-serif",
        },

        // Navigation
        navRow: {
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginTop: 8,
        },
        nextBtn: {
            background: "linear-gradient(135deg, #c9184a, #e07b39)",
            color: "#fff",
            border: "none",
            borderRadius: 12,
            padding: "13px 28px",
            fontSize: 15,
            fontWeight: 700,
            cursor: "pointer",
            letterSpacing: 0.3,
            transition: "opacity 0.2s, transform 0.2s",
            fontFamily: "'Georgia', serif",
            boxShadow: "0 4px 14px #c9184a44",
        },
        backBtn: {
            background: "transparent",
            color: "#9e7060",
            border: "1.5px solid #e0c4b8",
            borderRadius: 12,
            padding: "12px 22px",
            fontSize: 14,
            cursor: "pointer",
            fontFamily: "'Georgia', serif",
            transition: "background 0.2s",
        },
        searchBtn: {
            display: "flex",
            alignItems: "center",
            background: "linear-gradient(135deg, #c9184a, #ff6d00)",
            color: "#fff",
            border: "none",
            borderRadius: 14,
            padding: "15px 36px",
            fontSize: 17,
            fontWeight: 800,
            cursor: "pointer",
            letterSpacing: 0.5,
            boxShadow: "0 6px 20px #c9184a55",
            fontFamily: "'Georgia', serif",
            transition: "transform 0.2s",
        },

        // Done
        doneCard: {
            background: "rgba(255,255,255,0.95)",
            borderRadius: 24,
            padding: "clamp(32px, 6vw, 56px)",
            textAlign: "center",
            maxWidth: 500,
            width: "100%",
            boxShadow: "0 20px 60px #c9184a18",
            border: "1px solid #fce4ec",
            zIndex: 1,
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            gap: 12,
        },
        doneTitle: {
            fontSize: "clamp(1.5rem, 4vw, 2rem)",
            fontWeight: 900,
            color: "#1a0a00",
            margin: 0,
        },
        doneSub: {
            color: "#9e7060",
            fontSize: 15,
            margin: 0,
            fontFamily: "'Verdana', sans-serif",
            lineHeight: 1.6,
        },
        doneChips: {
            display: "flex",
            flexWrap: "wrap",
            justifyContent: "center",
            gap: 8,
            marginTop: 4,
        },
        resetBtn: {
            marginTop: 12,
            background: "linear-gradient(135deg, #c9184a, #e07b39)",
            color: "#fff",
            border: "none",
            borderRadius: 14,
            padding: "14px 32px",
            fontSize: 16,
            fontWeight: 800,
            cursor: "pointer",
            fontFamily: "'Georgia', serif",
            boxShadow: "0 6px 20px #c9184a44",
            letterSpacing: 0.5,
        },
    }
    return styles;
}